function density = getDensity(cordinates, integralImage)
    ed = integralImage(cordinates.maxX,cordinates.maxY) - ...
        integralImage(cordinates.maxX,cordinates.minY) - ...
        integralImage(cordinates.minX,cordinates.maxY) + ...
        integralImage(cordinates.minX,cordinates.minY);
    totalArea = (cordinates.maxX - cordinates.minX + 1) * ...
                (cordinates.maxY - cordinates.minY + 1);
    
    density = ed/totalArea;
end